export const data = [
  {
    id: 1,
    attributeName: "name",
    operations: [
      "name = ",
      "name != ",
      "name IN",
      "name NOT_IN",
      "name LIKE",
      "name NOT_LIKE",
      "name CONTAINS",
    ],
  },
  {
    id: 2,
    attributeName: "value",
    operations: [
      "value = ",
      "value != ",
      "value IN",
      "value NOT_IN",
      "value LIKE",
      "value NOT_LIKE",
      "value CONTAINS",
    ],
  },
  {
    id: 3,
    attributeName: "body",
    operations: [
      "body = ",
      "body != ",
      "body IN",
      "body NOT_IN",
      "body LIKE",
      "body NOT_LIKE",
      "body CONTAINS",
    ],
  },
  {
    id: 4,
    attributeName: "style",
    operations: [
      "style = ",
      "style != ",
      "style IN",
      "style NOT_IN",
      "style LIKE",
      "style NOT_LIKE",
      "style CONTAINS",
    ],
  },
  {
    id: 5,
    attributeName: "class",
    operations: [
      "class = ",
      "class != ",
      "class IN",
      "class NOT_IN",
      "class LIKE",
      "class NOT_LIKE",
      "class CONTAINS",
    ],
  },
  {
    id: 6,
    attributeName: "placeholder",
    operations: [
      "placeholder = ",
      "placeholder != ",
      "placeholder IN",
      "placeholder NOT_IN",
      "placeholder LIKE",
      "placeholder NOT_LIKE",
      "body CONTAINS",
    ],
  },
  {
    id: 7,
    attributeName: "alt",
    operations: [
      "alt = ",
      "alt != ",
      "alt IN",
      "alt NOT_IN",
      "alt LIKE",
      "alt NOT_LIKE",
      "alt CONTAINS",
    ],
  },
  {
    id: 8,
    attributeName: "checked",
    operations: [
      "checked = ",
      "checked != ",
      "checked IN",
      "checked NOT_IN",
      "checked LIKE",
      "checked NOT_LIKE",
      "checked CONTAINS",
    ],
  },
];
